### ISSUE TITLE
wouldn't it be better to use package.lock or yarn.lock?

### ISSUE THREAD

**Issue by dgreene1** [jsenv/importmap-node-module#5]
> @jsenv/node-module-import-map generates importMap for your project node_modules

I'm asking because the package.json is a range but the lock tells you the specific version you've locked to. So for my needs, I'd want the import map to be the version in yarn.lock, not the version range from package.json.

**Comment by dmail** [comment]
My first feeling was that filesystem is the source the truth to know where the files ares.
I also fear package.lock or yarn.lock formats might change depending on npm or yarn version. 

That being said I will give it a try.

The new version would generate importMap from package-lock.json or yarn.lock and log a warning if none are found.

It would also accept a new option that would generate import map from current filesystem state. That option would correspond to the current behaviour and would be false by default.

**Comment by dmail** [comment]
After reflexion using package lock as source of data would give exactly the same import map that using the filesystem. (Npm or yarn will respect your lock file so you get the same node modules).

And import map needs to read every package.json to check them main field to know the node module entry file. So it would not be possible to rely only on lock file to generate the import map.

**Comment by dmail** [comment]
Closing after inactivity, feel free discuss further.

**Comment by FluorescentHallucinogen** [comment]
> After reflexion using package lock would give the same import map that current implementation relying on filesystem.

@dmail Could you please provide more details on how exactly this is working now? Does it only use `node_modules`? Or does it use `package.json` (too)?

**Comment by dmail** [comment]
> Could you please provide more details on how exactly this is working now? Does it only use node_modules? Or does it use package.json (too)?

So there is 2 steps:
1. An importmap is generated using `package.json` + `node_modules/**/package.json`
2. (optional, if entry point(s) is specified) read entry point(s) to ensure importmap can be applied on all import found in js module files. This step can also "tree shake" importmap to keep only those actually used in the codebase

The script needs the root `package.json` and `node_modules/` to operate. The `package.json` files are important because they contain "main" and "exports" field which are used to know the import map values to associate with the package name.

In step 1, starting from `package-lock.json` instead of `package.json` would improve performance but would not change the resulting importmap. Because `package-lock.json` is a cached subset of the informations that can be deduced by traversing `node_modules`.

From importly:

> however, the package-lock.json is better because it includes subdependencies (and they're scoped, which means your dependencies can use different versions of a single subdependency)

According to this sentence there is a difference but I have a test with "different version of single dependency" and using `package.json` works fine: [tests/package_file_structures/package_inside](https://github.com/jsenv/importmap-node-module/tree/c2450ce1d078c48ed0afd22dbfa5804d95ce7a6a/tests/packages_file_structures/package_inside)

**Comment by FluorescentHallucinogen** [comment]
> So there is 2 steps

How about documenting this algorithm somewhere (e.g. in ReadMe)?

**Comment by dmail** [comment]
Documented in https://github.com/jsenv/importmap-node-module#how-it-works

**Comment by dmail** [comment]
Relying on filesystem to reconstruct what is in the lock files works (until I'm proven wrong). 
There is likely a perf improvment to get by using the lock file when available.
I'll keep that in mind but I don't plan to do this soon so I'll close this issue.

**Comment by FluorescentHallucinogen** [comment]
@dmail Do I understand correctly that generating import maps from lock file allows to not install dependencies at all (the generation will work even without `node_modules` folder)?

**Comment by dmail** [comment]
Unfortunately no.
The lock files contains only a subset of package.json fields. We need at least the "main" and "exports" field to generate the mappings

**Comment by dmail** [comment]
The lock file would just help to get the package.json files location without having to scan node_modules directory. But package Jason file contents still needs to be read
